sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_script:
  - yarn global add web-component-tester
  - gulp build
  - gulp build:tests
script: gulp lint & xvfb-run wct
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
