sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_script:
  - npm i
  - gulp build
  - gulp build:tests
script: gulp test:local
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
