sudo: required
dist: trusty
language: node_js
node_js:
- '6'
before_script:
  - npm i -g bower web-component-tester
  - bower install
  - gulp build:tests
script: xvfb-run wct
cache:
  directories:
    - node_modules
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
